services:
  watchdog_app:
    image: reg.sushi-market.dev/feedback-parser/app:test
    restart: unless-stopped
    volumes:
      - './storage/logs:/app/storage/logs'
      - './proxy-list.txt:/app/proxy-list.txt'
    env_file: ".env"
    environment:
      NODE_ENV: '${NODE_ENV}'
      APP_KEY: '${APP_KEY}'
      LOG_LEVEL: '${LOG_LEVEL}'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_DATABASE: '${DB_DATABASE}'

    ports:
      - '${PORT:-80}:80'

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: 'postgres:17-alpine'
    restart: unless-stopped
    ports:
      - ${FORWARD_DB_PORT:-5432}:5432
    environment:
      PGPASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [CMD, pg_isready, -q, -d, "${DB_DATABASE}", -U, "${DB_USERNAME}"]
      retries: 3
      timeout: 5s

volumes:
  postgres-data:
